name: Build docs

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build docs"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[speedup]
          pip install -U -r requirements/docs.txt
      
      - name: Build
        shell: bash
        run: |
          cd docs
          sphinx-build -b html -j auto -a source build/html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/build/html"

  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to GitHub Pages"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
